name: Fei Themes
url: https://github.com/ayee1616166/fei.github.io
description: Insert tagline here
github_repo: "https://github.com/ayee1616166/fei.github.io.git" # 用你的ID替换name

permalink: /themes/:title/

plugins: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
